App\Command\SearchCommand:
    properties:
        filePath:
            - NotBlank: ~
            - File:
                mimeTypes: [text/plain]
                notFoundMessage: Couldn't find file
                notReadableMessage: Couldn't read file
                mimeTypesMessage: Not propert file. Expecte text/plain mimeType file
            - Regex:
                pattern: '/.*\.txt$/'
                message: Not propert file. Expecte .txt file
        day:
            - NotBlank: ~
            - DateTime:
                format: d/m/y
        time:
            - NotBlank: ~
            - DateTime:
                format: H:i
                message: Time provided is incorrect. Should be in 24h format eg. 00:11
            - Regex:
                pattern: '/^\d{2}:\d{2}$/'
                message: Incorrect time format {{ value }}. Should be like mm:yy
        location:
            - NotBlank: ~
            - Regex:
                pattern: '/^[A-Za-z][a-zA-Z0-9]{1,}$/'
                message: Provided location {{ value }} is incorrect.
        cover:
            - NotBlank: ~
            - Range:
                min: 1
                minMessage: 'Must be positive number'
    getters:
        dateGreaterThanToday:
            - 'IsTrue':
                message: 'Incorrect time and/or day value. You can not search for current or previous days'
